version: '3.8'
services:
  app:
    container_name: app-dns_test
    build: .
    ports:
      - 4500:4500
    volumes:
      - ./app:/app
    depends_on:
      - db 
    network_mode: bridge
    
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=test-dns
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '33006:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/bd.sql:/docker-entrypoint-initdb.d/bd.sql

    network_mode: bridge
    
   
volumes:
  db:
    driver: local






  


 